include: package:lint/analysis_options.yaml

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false
    
    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # Can't pass constructors to functions (eg. as functions)
    prefer_constructors_over_static_methods: false

    # Model class code doesn't look as clean
    sort_constructors_first: false

    # main method uses async
    avoid_void_async: false


    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true
    # prefer_double_quotes: true

    # Good packages document everything
    # public_member_api_docs: true
    
    # Blindly follow the Flutter code style, which prefers types everywhere
    # always_specify_types: true

    # Const declaration for better performance
    prefer_const_constructors: true
  
    # Back to the 80s
    lines_longer_than_80_chars: true